### PR TITLE
ready for julia 1.10

### PR DESCRIPTION
**Pull request by thorek1**
SparseArrays doesnt have AdjOrTransDenseMatrix anymore in julia 1.10

here is a fix to get it to work

### CODE REVIEW

**Comment by thorek1** [comment]
kind reminder: Julia 1.10 is coming closer

it would be nice if you could look into this

your package is a downward compatibility of my package and prevents it from passing tests

**Comment by rasmushenningsson** [comment]
@jagot Do you have time to look at this? I'm currently on parental leave with very limit time on my hands. :)

**Comment by jagot** [comment]
Sorry for missing this PR, I will try to take a look at it during the weekend.

**Comment by jagot** [comment]
Merged in #13, thank you! I wanted to revert parts of the CI config, since if we declare compatibility with Julia 1.4, we better test on that version too.

**Pull request closed without merging**
